language: perl
perl:
  - 5.10
  - 5.12
  - 5.14
  - 5.16

env:
  - TEST_SUITE=sanity
  - TEST_SUITE=docs
  - TEST_SUITE=checksetup DB=mysql

matrix:
  exclude:
    - perl: 5.10
      env: TEST_SUITE=docs
    - perl: 5.12
      env: TEST_SUITE=docs
    - perl: 5.14
      env: TEST_SUITE=docs
    - perl: 5.10
      env: TEST_SUITE=checksetup DB=mysql
    - perl: 5.12
      env: TEST_SUITE=checksetup DB=mysql
    - perl: 5.14
      env: TEST_SUITE=checksetup DB=mysql

before_install:
  - git clone https://github.com/bugzilla/qa.git -b 4.4 qa

install: true

script: ./qa/travis.sh

after_failure:
  - sudo cat /var/log/apache2/error.log

notifications:
  irc:
    channels:
      - "irc.mozilla.org#qa-bugzilla"
      - "irc.mozilla.org#bugzilla"
    template:
      - "Bugzilla %{branch} : %{author} : %{message}"
      - "Commit Message : %{commit_message}"
      - "Commit Link : %{compare_url}"
      - "Build Link : %{build_url}"
  on_success: change
  on_failure: always
